### PR TITLE
Cross-post "A Rusty Bootstrapper" from IPFS blog

### PR DESCRIPTION
**Pull request by mxinden**

### CODE REVIEW

**Comment by mxinden** [comment]
@MarcoPolo and @marten-seemann: as discussed on Slack, here is the cross-post. Looks good to you?

//CC @p-shahi since you have shepherded most of the posts on this blog thus far.

**Comment by mxinden** [comment]
image

By clicking on the "Details" button, you can see a live preview.

**Comment by marten-seemann** [comment]
Maybe put the link below the summary: "Click here to go to the full blog post" or something like that.

Other than that, lgtm.

**Comment by p-shahi** [comment]
@mxinden My preference would be to follow the model of this PR https://github.com/libp2p/blog/pull/95 for cross posts like these. Are you ok if we close this in favor of #95 ?

**Comment by mxinden** [comment]
In favor of closing here! Thank you @p-shahi.

**Pull request closed without merging**
